/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as authIndexImport } from './routes/(auth)/index'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as auth500Import } from './routes/(auth)/500'

// Create Virtual Routes

const errors503LazyImport = createFileRoute('/(errors)/503')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const authSignUpLazyImport = createFileRoute('/(auth)/sign-up')()
const authSignIn2LazyImport = createFileRoute('/(auth)/sign-in-2')()
const authForgotPasswordLazyImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const AuthenticatedSettingsRouteLazyImport = createFileRoute(
  '/_authenticated/settings',
)()
const AuthenticatedUsersIndexLazyImport = createFileRoute(
  '/_authenticated/users/',
)()
const AuthenticatedTasksIndexLazyImport = createFileRoute(
  '/_authenticated/tasks/',
)()
const AuthenticatedSettingsIndexLazyImport = createFileRoute(
  '/_authenticated/settings/',
)()
const AuthenticatedProductsIndexLazyImport = createFileRoute(
  '/_authenticated/products/',
)()
const AuthenticatedProductContentsIndexLazyImport = createFileRoute(
  '/_authenticated/product-contents/',
)()
const AuthenticatedProductContentFeaturesIndexLazyImport = createFileRoute(
  '/_authenticated/product-content-features/',
)()
const AuthenticatedProductContentDisplaysIndexLazyImport = createFileRoute(
  '/_authenticated/product-content-displays/',
)()
const AuthenticatedProductContentDetailsIndexLazyImport = createFileRoute(
  '/_authenticated/product-content-details/',
)()
const AuthenticatedProductCategorySecondsIndexLazyImport = createFileRoute(
  '/_authenticated/product-category-seconds/',
)()
const AuthenticatedProductCategoryFirstsIndexLazyImport = createFileRoute(
  '/_authenticated/product-category-firsts/',
)()
const AuthenticatedProductCartsIndexLazyImport = createFileRoute(
  '/_authenticated/product-carts/',
)()
const AuthenticatedHelpCenterIndexLazyImport = createFileRoute(
  '/_authenticated/help-center/',
)()
const AuthenticatedDashboardsIndexLazyImport = createFileRoute(
  '/_authenticated/dashboards/',
)()
const AuthenticatedCustomersIndexLazyImport = createFileRoute(
  '/_authenticated/customers/',
)()
const AuthenticatedChatsIndexLazyImport = createFileRoute(
  '/_authenticated/chats/',
)()
const AuthenticatedBrandsIndexLazyImport = createFileRoute(
  '/_authenticated/brands/',
)()
const AuthenticatedAppsIndexLazyImport = createFileRoute(
  '/_authenticated/apps/',
)()
const AuthenticatedSettingsNotificationsLazyImport = createFileRoute(
  '/_authenticated/settings/notifications',
)()
const AuthenticatedSettingsDisplayLazyImport = createFileRoute(
  '/_authenticated/settings/display',
)()
const AuthenticatedSettingsAppearanceLazyImport = createFileRoute(
  '/_authenticated/settings/appearance',
)()
const AuthenticatedSettingsAccountLazyImport = createFileRoute(
  '/_authenticated/settings/account',
)()
const AuthenticatedProductContentsCreateLazyImport = createFileRoute(
  '/_authenticated/product-contents/create',
)()
const AuthenticatedProductContentFeaturesCreateLazyImport = createFileRoute(
  '/_authenticated/product-content-features/create',
)()
const AuthenticatedProductContentDisplaysCreateLazyImport = createFileRoute(
  '/_authenticated/product-content-displays/create',
)()
const AuthenticatedProductContentDetailsCreateLazyImport = createFileRoute(
  '/_authenticated/product-content-details/create',
)()
const AuthenticatedProductCategorySecondsCreateLazyImport = createFileRoute(
  '/_authenticated/product-category-seconds/create',
)()
const AuthenticatedProductCategoryFirstsCreateLazyImport = createFileRoute(
  '/_authenticated/product-category-firsts/create',
)()
const AuthenticatedCustomersCustomerCrudLazyImport = createFileRoute(
  '/_authenticated/customers/customerCrud',
)()
const AuthenticatedBrandsCreateLazyImport = createFileRoute(
  '/_authenticated/brands/create',
)()
const AuthenticatedProductContentsIdEditLazyImport = createFileRoute(
  '/_authenticated/product-contents/$id/edit',
)()
const AuthenticatedProductContentFeaturesIdEditLazyImport = createFileRoute(
  '/_authenticated/product-content-features/$id/edit',
)()
const AuthenticatedProductContentDisplaysIdEditLazyImport = createFileRoute(
  '/_authenticated/product-content-displays/$id/edit',
)()
const AuthenticatedProductContentDetailsIdEditLazyImport = createFileRoute(
  '/_authenticated/product-content-details/$id/edit',
)()
const AuthenticatedProductCategorySecondsIdEditLazyImport = createFileRoute(
  '/_authenticated/product-category-seconds/$id/edit',
)()
const AuthenticatedProductCategoryFirstsIdEditLazyImport = createFileRoute(
  '/_authenticated/product-category-firsts/$id/edit',
)()
const AuthenticatedBrandsIdEditLazyImport = createFileRoute(
  '/_authenticated/brands/$id/edit',
)()

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const authIndexRoute = authIndexImport.update({
  id: '/(auth)/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const errors503LazyRoute = errors503LazyImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const authSignUpLazyRoute = authSignUpLazyImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))

const authSignIn2LazyRoute = authSignIn2LazyImport
  .update({
    id: '/(auth)/sign-in-2',
    path: '/sign-in-2',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-in-2.lazy').then((d) => d.Route))

const authForgotPasswordLazyRoute = authForgotPasswordLazyImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsRouteLazyRoute =
  AuthenticatedSettingsRouteLazyImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/route.lazy').then((d) => d.Route),
  )

const AuthSignInRoute = AuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const auth500Route = auth500Import.update({
  id: '/(auth)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedUsersIndexLazyRoute =
  AuthenticatedUsersIndexLazyImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/users/index.lazy').then((d) => d.Route),
  )

const AuthenticatedTasksIndexLazyRoute =
  AuthenticatedTasksIndexLazyImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/tasks/index.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsIndexLazyRoute =
  AuthenticatedSettingsIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/index.lazy').then((d) => d.Route),
  )

const AuthenticatedProductsIndexLazyRoute =
  AuthenticatedProductsIndexLazyImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/products/index.lazy').then((d) => d.Route),
  )

const AuthenticatedProductContentsIndexLazyRoute =
  AuthenticatedProductContentsIndexLazyImport.update({
    id: '/product-contents/',
    path: '/product-contents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product-contents/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductContentFeaturesIndexLazyRoute =
  AuthenticatedProductContentFeaturesIndexLazyImport.update({
    id: '/product-content-features/',
    path: '/product-content-features/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product-content-features/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductContentDisplaysIndexLazyRoute =
  AuthenticatedProductContentDisplaysIndexLazyImport.update({
    id: '/product-content-displays/',
    path: '/product-content-displays/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product-content-displays/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductContentDetailsIndexLazyRoute =
  AuthenticatedProductContentDetailsIndexLazyImport.update({
    id: '/product-content-details/',
    path: '/product-content-details/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product-content-details/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductCategorySecondsIndexLazyRoute =
  AuthenticatedProductCategorySecondsIndexLazyImport.update({
    id: '/product-category-seconds/',
    path: '/product-category-seconds/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product-category-seconds/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductCategoryFirstsIndexLazyRoute =
  AuthenticatedProductCategoryFirstsIndexLazyImport.update({
    id: '/product-category-firsts/',
    path: '/product-category-firsts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product-category-firsts/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductCartsIndexLazyRoute =
  AuthenticatedProductCartsIndexLazyImport.update({
    id: '/product-carts/',
    path: '/product-carts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product-carts/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedHelpCenterIndexLazyRoute =
  AuthenticatedHelpCenterIndexLazyImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/help-center/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDashboardsIndexLazyRoute =
  AuthenticatedDashboardsIndexLazyImport.update({
    id: '/dashboards/',
    path: '/dashboards/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboards/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedCustomersIndexLazyRoute =
  AuthenticatedCustomersIndexLazyImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/customers/index.lazy').then((d) => d.Route),
  )

const AuthenticatedChatsIndexLazyRoute =
  AuthenticatedChatsIndexLazyImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/chats/index.lazy').then((d) => d.Route),
  )

const AuthenticatedBrandsIndexLazyRoute =
  AuthenticatedBrandsIndexLazyImport.update({
    id: '/brands/',
    path: '/brands/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/brands/index.lazy').then((d) => d.Route),
  )

const AuthenticatedAppsIndexLazyRoute = AuthenticatedAppsIndexLazyImport.update(
  {
    id: '/apps/',
    path: '/apps/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/apps/index.lazy').then((d) => d.Route),
)

const AuthenticatedSettingsNotificationsLazyRoute =
  AuthenticatedSettingsNotificationsLazyImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/notifications.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsDisplayLazyRoute =
  AuthenticatedSettingsDisplayLazyImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/display.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAppearanceLazyRoute =
  AuthenticatedSettingsAppearanceLazyImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/appearance.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAccountLazyRoute =
  AuthenticatedSettingsAccountLazyImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/account.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductContentsCreateLazyRoute =
  AuthenticatedProductContentsCreateLazyImport.update({
    id: '/product-contents/create',
    path: '/product-contents/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product-contents/create.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductContentFeaturesCreateLazyRoute =
  AuthenticatedProductContentFeaturesCreateLazyImport.update({
    id: '/product-content-features/create',
    path: '/product-content-features/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product-content-features/create.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductContentDisplaysCreateLazyRoute =
  AuthenticatedProductContentDisplaysCreateLazyImport.update({
    id: '/product-content-displays/create',
    path: '/product-content-displays/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product-content-displays/create.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductContentDetailsCreateLazyRoute =
  AuthenticatedProductContentDetailsCreateLazyImport.update({
    id: '/product-content-details/create',
    path: '/product-content-details/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product-content-details/create.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductCategorySecondsCreateLazyRoute =
  AuthenticatedProductCategorySecondsCreateLazyImport.update({
    id: '/product-category-seconds/create',
    path: '/product-category-seconds/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product-category-seconds/create.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductCategoryFirstsCreateLazyRoute =
  AuthenticatedProductCategoryFirstsCreateLazyImport.update({
    id: '/product-category-firsts/create',
    path: '/product-category-firsts/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product-category-firsts/create.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedCustomersCustomerCrudLazyRoute =
  AuthenticatedCustomersCustomerCrudLazyImport.update({
    id: '/customers/customerCrud',
    path: '/customers/customerCrud',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/customers/customerCrud.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedBrandsCreateLazyRoute =
  AuthenticatedBrandsCreateLazyImport.update({
    id: '/brands/create',
    path: '/brands/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/brands/create.lazy').then((d) => d.Route),
  )

const AuthenticatedProductContentsIdEditLazyRoute =
  AuthenticatedProductContentsIdEditLazyImport.update({
    id: '/product-contents/$id/edit',
    path: '/product-contents/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product-contents/$id/edit.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductContentFeaturesIdEditLazyRoute =
  AuthenticatedProductContentFeaturesIdEditLazyImport.update({
    id: '/product-content-features/$id/edit',
    path: '/product-content-features/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/product-content-features/$id/edit.lazy'
    ).then((d) => d.Route),
  )

const AuthenticatedProductContentDisplaysIdEditLazyRoute =
  AuthenticatedProductContentDisplaysIdEditLazyImport.update({
    id: '/product-content-displays/$id/edit',
    path: '/product-content-displays/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/product-content-displays/$id/edit.lazy'
    ).then((d) => d.Route),
  )

const AuthenticatedProductContentDetailsIdEditLazyRoute =
  AuthenticatedProductContentDetailsIdEditLazyImport.update({
    id: '/product-content-details/$id/edit',
    path: '/product-content-details/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/product-content-details/$id/edit.lazy'
    ).then((d) => d.Route),
  )

const AuthenticatedProductCategorySecondsIdEditLazyRoute =
  AuthenticatedProductCategorySecondsIdEditLazyImport.update({
    id: '/product-category-seconds/$id/edit',
    path: '/product-category-seconds/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/product-category-seconds/$id/edit.lazy'
    ).then((d) => d.Route),
  )

const AuthenticatedProductCategoryFirstsIdEditLazyRoute =
  AuthenticatedProductCategoryFirstsIdEditLazyImport.update({
    id: '/product-category-firsts/$id/edit',
    path: '/product-category-firsts/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/product-category-firsts/$id/edit.lazy'
    ).then((d) => d.Route),
  )

const AuthenticatedBrandsIdEditLazyRoute =
  AuthenticatedBrandsIdEditLazyImport.update({
    id: '/brands/$id/edit',
    path: '/brands/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/brands/$id/edit.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/500': {
      id: '/(auth)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof auth500Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2LazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/brands/create': {
      id: '/_authenticated/brands/create'
      path: '/brands/create'
      fullPath: '/brands/create'
      preLoaderRoute: typeof AuthenticatedBrandsCreateLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/customers/customerCrud': {
      id: '/_authenticated/customers/customerCrud'
      path: '/customers/customerCrud'
      fullPath: '/customers/customerCrud'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerCrudLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-category-firsts/create': {
      id: '/_authenticated/product-category-firsts/create'
      path: '/product-category-firsts/create'
      fullPath: '/product-category-firsts/create'
      preLoaderRoute: typeof AuthenticatedProductCategoryFirstsCreateLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-category-seconds/create': {
      id: '/_authenticated/product-category-seconds/create'
      path: '/product-category-seconds/create'
      fullPath: '/product-category-seconds/create'
      preLoaderRoute: typeof AuthenticatedProductCategorySecondsCreateLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-content-details/create': {
      id: '/_authenticated/product-content-details/create'
      path: '/product-content-details/create'
      fullPath: '/product-content-details/create'
      preLoaderRoute: typeof AuthenticatedProductContentDetailsCreateLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-content-displays/create': {
      id: '/_authenticated/product-content-displays/create'
      path: '/product-content-displays/create'
      fullPath: '/product-content-displays/create'
      preLoaderRoute: typeof AuthenticatedProductContentDisplaysCreateLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-content-features/create': {
      id: '/_authenticated/product-content-features/create'
      path: '/product-content-features/create'
      fullPath: '/product-content-features/create'
      preLoaderRoute: typeof AuthenticatedProductContentFeaturesCreateLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-contents/create': {
      id: '/_authenticated/product-contents/create'
      path: '/product-contents/create'
      fullPath: '/product-contents/create'
      preLoaderRoute: typeof AuthenticatedProductContentsCreateLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/brands/': {
      id: '/_authenticated/brands/'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AuthenticatedBrandsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/dashboards/': {
      id: '/_authenticated/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AuthenticatedDashboardsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-carts/': {
      id: '/_authenticated/product-carts/'
      path: '/product-carts'
      fullPath: '/product-carts'
      preLoaderRoute: typeof AuthenticatedProductCartsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-category-firsts/': {
      id: '/_authenticated/product-category-firsts/'
      path: '/product-category-firsts'
      fullPath: '/product-category-firsts'
      preLoaderRoute: typeof AuthenticatedProductCategoryFirstsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-category-seconds/': {
      id: '/_authenticated/product-category-seconds/'
      path: '/product-category-seconds'
      fullPath: '/product-category-seconds'
      preLoaderRoute: typeof AuthenticatedProductCategorySecondsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-content-details/': {
      id: '/_authenticated/product-content-details/'
      path: '/product-content-details'
      fullPath: '/product-content-details'
      preLoaderRoute: typeof AuthenticatedProductContentDetailsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-content-displays/': {
      id: '/_authenticated/product-content-displays/'
      path: '/product-content-displays'
      fullPath: '/product-content-displays'
      preLoaderRoute: typeof AuthenticatedProductContentDisplaysIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-content-features/': {
      id: '/_authenticated/product-content-features/'
      path: '/product-content-features'
      fullPath: '/product-content-features'
      preLoaderRoute: typeof AuthenticatedProductContentFeaturesIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-contents/': {
      id: '/_authenticated/product-contents/'
      path: '/product-contents'
      fullPath: '/product-contents'
      preLoaderRoute: typeof AuthenticatedProductContentsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/brands/$id/edit': {
      id: '/_authenticated/brands/$id/edit'
      path: '/brands/$id/edit'
      fullPath: '/brands/$id/edit'
      preLoaderRoute: typeof AuthenticatedBrandsIdEditLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-category-firsts/$id/edit': {
      id: '/_authenticated/product-category-firsts/$id/edit'
      path: '/product-category-firsts/$id/edit'
      fullPath: '/product-category-firsts/$id/edit'
      preLoaderRoute: typeof AuthenticatedProductCategoryFirstsIdEditLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-category-seconds/$id/edit': {
      id: '/_authenticated/product-category-seconds/$id/edit'
      path: '/product-category-seconds/$id/edit'
      fullPath: '/product-category-seconds/$id/edit'
      preLoaderRoute: typeof AuthenticatedProductCategorySecondsIdEditLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-content-details/$id/edit': {
      id: '/_authenticated/product-content-details/$id/edit'
      path: '/product-content-details/$id/edit'
      fullPath: '/product-content-details/$id/edit'
      preLoaderRoute: typeof AuthenticatedProductContentDetailsIdEditLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-content-displays/$id/edit': {
      id: '/_authenticated/product-content-displays/$id/edit'
      path: '/product-content-displays/$id/edit'
      fullPath: '/product-content-displays/$id/edit'
      preLoaderRoute: typeof AuthenticatedProductContentDisplaysIdEditLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-content-features/$id/edit': {
      id: '/_authenticated/product-content-features/$id/edit'
      path: '/product-content-features/$id/edit'
      fullPath: '/product-content-features/$id/edit'
      preLoaderRoute: typeof AuthenticatedProductContentFeaturesIdEditLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product-contents/$id/edit': {
      id: '/_authenticated/product-contents/$id/edit'
      path: '/product-contents/$id/edit'
      fullPath: '/product-contents/$id/edit'
      preLoaderRoute: typeof AuthenticatedProductContentsIdEditLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedSettingsRouteLazyRouteChildren {
  AuthenticatedSettingsAccountLazyRoute: typeof AuthenticatedSettingsAccountLazyRoute
  AuthenticatedSettingsAppearanceLazyRoute: typeof AuthenticatedSettingsAppearanceLazyRoute
  AuthenticatedSettingsDisplayLazyRoute: typeof AuthenticatedSettingsDisplayLazyRoute
  AuthenticatedSettingsNotificationsLazyRoute: typeof AuthenticatedSettingsNotificationsLazyRoute
  AuthenticatedSettingsIndexLazyRoute: typeof AuthenticatedSettingsIndexLazyRoute
}

const AuthenticatedSettingsRouteLazyRouteChildren: AuthenticatedSettingsRouteLazyRouteChildren =
  {
    AuthenticatedSettingsAccountLazyRoute:
      AuthenticatedSettingsAccountLazyRoute,
    AuthenticatedSettingsAppearanceLazyRoute:
      AuthenticatedSettingsAppearanceLazyRoute,
    AuthenticatedSettingsDisplayLazyRoute:
      AuthenticatedSettingsDisplayLazyRoute,
    AuthenticatedSettingsNotificationsLazyRoute:
      AuthenticatedSettingsNotificationsLazyRoute,
    AuthenticatedSettingsIndexLazyRoute: AuthenticatedSettingsIndexLazyRoute,
  }

const AuthenticatedSettingsRouteLazyRouteWithChildren =
  AuthenticatedSettingsRouteLazyRoute._addFileChildren(
    AuthenticatedSettingsRouteLazyRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteLazyRoute: typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  AuthenticatedBrandsCreateLazyRoute: typeof AuthenticatedBrandsCreateLazyRoute
  AuthenticatedCustomersCustomerCrudLazyRoute: typeof AuthenticatedCustomersCustomerCrudLazyRoute
  AuthenticatedProductCategoryFirstsCreateLazyRoute: typeof AuthenticatedProductCategoryFirstsCreateLazyRoute
  AuthenticatedProductCategorySecondsCreateLazyRoute: typeof AuthenticatedProductCategorySecondsCreateLazyRoute
  AuthenticatedProductContentDetailsCreateLazyRoute: typeof AuthenticatedProductContentDetailsCreateLazyRoute
  AuthenticatedProductContentDisplaysCreateLazyRoute: typeof AuthenticatedProductContentDisplaysCreateLazyRoute
  AuthenticatedProductContentFeaturesCreateLazyRoute: typeof AuthenticatedProductContentFeaturesCreateLazyRoute
  AuthenticatedProductContentsCreateLazyRoute: typeof AuthenticatedProductContentsCreateLazyRoute
  AuthenticatedAppsIndexLazyRoute: typeof AuthenticatedAppsIndexLazyRoute
  AuthenticatedBrandsIndexLazyRoute: typeof AuthenticatedBrandsIndexLazyRoute
  AuthenticatedChatsIndexLazyRoute: typeof AuthenticatedChatsIndexLazyRoute
  AuthenticatedCustomersIndexLazyRoute: typeof AuthenticatedCustomersIndexLazyRoute
  AuthenticatedDashboardsIndexLazyRoute: typeof AuthenticatedDashboardsIndexLazyRoute
  AuthenticatedHelpCenterIndexLazyRoute: typeof AuthenticatedHelpCenterIndexLazyRoute
  AuthenticatedProductCartsIndexLazyRoute: typeof AuthenticatedProductCartsIndexLazyRoute
  AuthenticatedProductCategoryFirstsIndexLazyRoute: typeof AuthenticatedProductCategoryFirstsIndexLazyRoute
  AuthenticatedProductCategorySecondsIndexLazyRoute: typeof AuthenticatedProductCategorySecondsIndexLazyRoute
  AuthenticatedProductContentDetailsIndexLazyRoute: typeof AuthenticatedProductContentDetailsIndexLazyRoute
  AuthenticatedProductContentDisplaysIndexLazyRoute: typeof AuthenticatedProductContentDisplaysIndexLazyRoute
  AuthenticatedProductContentFeaturesIndexLazyRoute: typeof AuthenticatedProductContentFeaturesIndexLazyRoute
  AuthenticatedProductContentsIndexLazyRoute: typeof AuthenticatedProductContentsIndexLazyRoute
  AuthenticatedProductsIndexLazyRoute: typeof AuthenticatedProductsIndexLazyRoute
  AuthenticatedTasksIndexLazyRoute: typeof AuthenticatedTasksIndexLazyRoute
  AuthenticatedUsersIndexLazyRoute: typeof AuthenticatedUsersIndexLazyRoute
  AuthenticatedBrandsIdEditLazyRoute: typeof AuthenticatedBrandsIdEditLazyRoute
  AuthenticatedProductCategoryFirstsIdEditLazyRoute: typeof AuthenticatedProductCategoryFirstsIdEditLazyRoute
  AuthenticatedProductCategorySecondsIdEditLazyRoute: typeof AuthenticatedProductCategorySecondsIdEditLazyRoute
  AuthenticatedProductContentDetailsIdEditLazyRoute: typeof AuthenticatedProductContentDetailsIdEditLazyRoute
  AuthenticatedProductContentDisplaysIdEditLazyRoute: typeof AuthenticatedProductContentDisplaysIdEditLazyRoute
  AuthenticatedProductContentFeaturesIdEditLazyRoute: typeof AuthenticatedProductContentFeaturesIdEditLazyRoute
  AuthenticatedProductContentsIdEditLazyRoute: typeof AuthenticatedProductContentsIdEditLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteLazyRoute:
    AuthenticatedSettingsRouteLazyRouteWithChildren,
  AuthenticatedBrandsCreateLazyRoute: AuthenticatedBrandsCreateLazyRoute,
  AuthenticatedCustomersCustomerCrudLazyRoute:
    AuthenticatedCustomersCustomerCrudLazyRoute,
  AuthenticatedProductCategoryFirstsCreateLazyRoute:
    AuthenticatedProductCategoryFirstsCreateLazyRoute,
  AuthenticatedProductCategorySecondsCreateLazyRoute:
    AuthenticatedProductCategorySecondsCreateLazyRoute,
  AuthenticatedProductContentDetailsCreateLazyRoute:
    AuthenticatedProductContentDetailsCreateLazyRoute,
  AuthenticatedProductContentDisplaysCreateLazyRoute:
    AuthenticatedProductContentDisplaysCreateLazyRoute,
  AuthenticatedProductContentFeaturesCreateLazyRoute:
    AuthenticatedProductContentFeaturesCreateLazyRoute,
  AuthenticatedProductContentsCreateLazyRoute:
    AuthenticatedProductContentsCreateLazyRoute,
  AuthenticatedAppsIndexLazyRoute: AuthenticatedAppsIndexLazyRoute,
  AuthenticatedBrandsIndexLazyRoute: AuthenticatedBrandsIndexLazyRoute,
  AuthenticatedChatsIndexLazyRoute: AuthenticatedChatsIndexLazyRoute,
  AuthenticatedCustomersIndexLazyRoute: AuthenticatedCustomersIndexLazyRoute,
  AuthenticatedDashboardsIndexLazyRoute: AuthenticatedDashboardsIndexLazyRoute,
  AuthenticatedHelpCenterIndexLazyRoute: AuthenticatedHelpCenterIndexLazyRoute,
  AuthenticatedProductCartsIndexLazyRoute:
    AuthenticatedProductCartsIndexLazyRoute,
  AuthenticatedProductCategoryFirstsIndexLazyRoute:
    AuthenticatedProductCategoryFirstsIndexLazyRoute,
  AuthenticatedProductCategorySecondsIndexLazyRoute:
    AuthenticatedProductCategorySecondsIndexLazyRoute,
  AuthenticatedProductContentDetailsIndexLazyRoute:
    AuthenticatedProductContentDetailsIndexLazyRoute,
  AuthenticatedProductContentDisplaysIndexLazyRoute:
    AuthenticatedProductContentDisplaysIndexLazyRoute,
  AuthenticatedProductContentFeaturesIndexLazyRoute:
    AuthenticatedProductContentFeaturesIndexLazyRoute,
  AuthenticatedProductContentsIndexLazyRoute:
    AuthenticatedProductContentsIndexLazyRoute,
  AuthenticatedProductsIndexLazyRoute: AuthenticatedProductsIndexLazyRoute,
  AuthenticatedTasksIndexLazyRoute: AuthenticatedTasksIndexLazyRoute,
  AuthenticatedUsersIndexLazyRoute: AuthenticatedUsersIndexLazyRoute,
  AuthenticatedBrandsIdEditLazyRoute: AuthenticatedBrandsIdEditLazyRoute,
  AuthenticatedProductCategoryFirstsIdEditLazyRoute:
    AuthenticatedProductCategoryFirstsIdEditLazyRoute,
  AuthenticatedProductCategorySecondsIdEditLazyRoute:
    AuthenticatedProductCategorySecondsIdEditLazyRoute,
  AuthenticatedProductContentDetailsIdEditLazyRoute:
    AuthenticatedProductContentDetailsIdEditLazyRoute,
  AuthenticatedProductContentDisplaysIdEditLazyRoute:
    AuthenticatedProductContentDisplaysIdEditLazyRoute,
  AuthenticatedProductContentFeaturesIdEditLazyRoute:
    AuthenticatedProductContentFeaturesIdEditLazyRoute,
  AuthenticatedProductContentsIdEditLazyRoute:
    AuthenticatedProductContentsIdEditLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof authIndexRoute
  '/brands/create': typeof AuthenticatedBrandsCreateLazyRoute
  '/customers/customerCrud': typeof AuthenticatedCustomersCustomerCrudLazyRoute
  '/product-category-firsts/create': typeof AuthenticatedProductCategoryFirstsCreateLazyRoute
  '/product-category-seconds/create': typeof AuthenticatedProductCategorySecondsCreateLazyRoute
  '/product-content-details/create': typeof AuthenticatedProductContentDetailsCreateLazyRoute
  '/product-content-displays/create': typeof AuthenticatedProductContentDisplaysCreateLazyRoute
  '/product-content-features/create': typeof AuthenticatedProductContentFeaturesCreateLazyRoute
  '/product-contents/create': typeof AuthenticatedProductContentsCreateLazyRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/apps': typeof AuthenticatedAppsIndexLazyRoute
  '/brands': typeof AuthenticatedBrandsIndexLazyRoute
  '/chats': typeof AuthenticatedChatsIndexLazyRoute
  '/customers': typeof AuthenticatedCustomersIndexLazyRoute
  '/dashboards': typeof AuthenticatedDashboardsIndexLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/product-carts': typeof AuthenticatedProductCartsIndexLazyRoute
  '/product-category-firsts': typeof AuthenticatedProductCategoryFirstsIndexLazyRoute
  '/product-category-seconds': typeof AuthenticatedProductCategorySecondsIndexLazyRoute
  '/product-content-details': typeof AuthenticatedProductContentDetailsIndexLazyRoute
  '/product-content-displays': typeof AuthenticatedProductContentDisplaysIndexLazyRoute
  '/product-content-features': typeof AuthenticatedProductContentFeaturesIndexLazyRoute
  '/product-contents': typeof AuthenticatedProductContentsIndexLazyRoute
  '/products': typeof AuthenticatedProductsIndexLazyRoute
  '/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/tasks': typeof AuthenticatedTasksIndexLazyRoute
  '/users': typeof AuthenticatedUsersIndexLazyRoute
  '/brands/$id/edit': typeof AuthenticatedBrandsIdEditLazyRoute
  '/product-category-firsts/$id/edit': typeof AuthenticatedProductCategoryFirstsIdEditLazyRoute
  '/product-category-seconds/$id/edit': typeof AuthenticatedProductCategorySecondsIdEditLazyRoute
  '/product-content-details/$id/edit': typeof AuthenticatedProductContentDetailsIdEditLazyRoute
  '/product-content-displays/$id/edit': typeof AuthenticatedProductContentDisplaysIdEditLazyRoute
  '/product-content-features/$id/edit': typeof AuthenticatedProductContentFeaturesIdEditLazyRoute
  '/product-contents/$id/edit': typeof AuthenticatedProductContentsIdEditLazyRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof authIndexRoute
  '/brands/create': typeof AuthenticatedBrandsCreateLazyRoute
  '/customers/customerCrud': typeof AuthenticatedCustomersCustomerCrudLazyRoute
  '/product-category-firsts/create': typeof AuthenticatedProductCategoryFirstsCreateLazyRoute
  '/product-category-seconds/create': typeof AuthenticatedProductCategorySecondsCreateLazyRoute
  '/product-content-details/create': typeof AuthenticatedProductContentDetailsCreateLazyRoute
  '/product-content-displays/create': typeof AuthenticatedProductContentDisplaysCreateLazyRoute
  '/product-content-features/create': typeof AuthenticatedProductContentFeaturesCreateLazyRoute
  '/product-contents/create': typeof AuthenticatedProductContentsCreateLazyRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/apps': typeof AuthenticatedAppsIndexLazyRoute
  '/brands': typeof AuthenticatedBrandsIndexLazyRoute
  '/chats': typeof AuthenticatedChatsIndexLazyRoute
  '/customers': typeof AuthenticatedCustomersIndexLazyRoute
  '/dashboards': typeof AuthenticatedDashboardsIndexLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/product-carts': typeof AuthenticatedProductCartsIndexLazyRoute
  '/product-category-firsts': typeof AuthenticatedProductCategoryFirstsIndexLazyRoute
  '/product-category-seconds': typeof AuthenticatedProductCategorySecondsIndexLazyRoute
  '/product-content-details': typeof AuthenticatedProductContentDetailsIndexLazyRoute
  '/product-content-displays': typeof AuthenticatedProductContentDisplaysIndexLazyRoute
  '/product-content-features': typeof AuthenticatedProductContentFeaturesIndexLazyRoute
  '/product-contents': typeof AuthenticatedProductContentsIndexLazyRoute
  '/products': typeof AuthenticatedProductsIndexLazyRoute
  '/settings': typeof AuthenticatedSettingsIndexLazyRoute
  '/tasks': typeof AuthenticatedTasksIndexLazyRoute
  '/users': typeof AuthenticatedUsersIndexLazyRoute
  '/brands/$id/edit': typeof AuthenticatedBrandsIdEditLazyRoute
  '/product-category-firsts/$id/edit': typeof AuthenticatedProductCategoryFirstsIdEditLazyRoute
  '/product-category-seconds/$id/edit': typeof AuthenticatedProductCategorySecondsIdEditLazyRoute
  '/product-content-details/$id/edit': typeof AuthenticatedProductContentDetailsIdEditLazyRoute
  '/product-content-displays/$id/edit': typeof AuthenticatedProductContentDisplaysIdEditLazyRoute
  '/product-content-features/$id/edit': typeof AuthenticatedProductContentFeaturesIdEditLazyRoute
  '/product-contents/$id/edit': typeof AuthenticatedProductContentsIdEditLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/500': typeof auth500Route
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-in-2': typeof authSignIn2LazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/(auth)/': typeof authIndexRoute
  '/_authenticated/brands/create': typeof AuthenticatedBrandsCreateLazyRoute
  '/_authenticated/customers/customerCrud': typeof AuthenticatedCustomersCustomerCrudLazyRoute
  '/_authenticated/product-category-firsts/create': typeof AuthenticatedProductCategoryFirstsCreateLazyRoute
  '/_authenticated/product-category-seconds/create': typeof AuthenticatedProductCategorySecondsCreateLazyRoute
  '/_authenticated/product-content-details/create': typeof AuthenticatedProductContentDetailsCreateLazyRoute
  '/_authenticated/product-content-displays/create': typeof AuthenticatedProductContentDisplaysCreateLazyRoute
  '/_authenticated/product-content-features/create': typeof AuthenticatedProductContentFeaturesCreateLazyRoute
  '/_authenticated/product-contents/create': typeof AuthenticatedProductContentsCreateLazyRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexLazyRoute
  '/_authenticated/brands/': typeof AuthenticatedBrandsIndexLazyRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexLazyRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexLazyRoute
  '/_authenticated/dashboards/': typeof AuthenticatedDashboardsIndexLazyRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/_authenticated/product-carts/': typeof AuthenticatedProductCartsIndexLazyRoute
  '/_authenticated/product-category-firsts/': typeof AuthenticatedProductCategoryFirstsIndexLazyRoute
  '/_authenticated/product-category-seconds/': typeof AuthenticatedProductCategorySecondsIndexLazyRoute
  '/_authenticated/product-content-details/': typeof AuthenticatedProductContentDetailsIndexLazyRoute
  '/_authenticated/product-content-displays/': typeof AuthenticatedProductContentDisplaysIndexLazyRoute
  '/_authenticated/product-content-features/': typeof AuthenticatedProductContentFeaturesIndexLazyRoute
  '/_authenticated/product-contents/': typeof AuthenticatedProductContentsIndexLazyRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexLazyRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexLazyRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexLazyRoute
  '/_authenticated/brands/$id/edit': typeof AuthenticatedBrandsIdEditLazyRoute
  '/_authenticated/product-category-firsts/$id/edit': typeof AuthenticatedProductCategoryFirstsIdEditLazyRoute
  '/_authenticated/product-category-seconds/$id/edit': typeof AuthenticatedProductCategorySecondsIdEditLazyRoute
  '/_authenticated/product-content-details/$id/edit': typeof AuthenticatedProductContentDetailsIdEditLazyRoute
  '/_authenticated/product-content-displays/$id/edit': typeof AuthenticatedProductContentDisplaysIdEditLazyRoute
  '/_authenticated/product-content-features/$id/edit': typeof AuthenticatedProductContentFeaturesIdEditLazyRoute
  '/_authenticated/product-contents/$id/edit': typeof AuthenticatedProductContentsIdEditLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/500'
    | '/otp'
    | '/sign-in'
    | '/auth/sign-in'
    | '/settings'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/'
    | '/brands/create'
    | '/customers/customerCrud'
    | '/product-category-firsts/create'
    | '/product-category-seconds/create'
    | '/product-content-details/create'
    | '/product-content-displays/create'
    | '/product-content-features/create'
    | '/product-contents/create'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/brands'
    | '/chats'
    | '/customers'
    | '/dashboards'
    | '/help-center'
    | '/product-carts'
    | '/product-category-firsts'
    | '/product-category-seconds'
    | '/product-content-details'
    | '/product-content-displays'
    | '/product-content-features'
    | '/product-contents'
    | '/products'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/brands/$id/edit'
    | '/product-category-firsts/$id/edit'
    | '/product-category-seconds/$id/edit'
    | '/product-content-details/$id/edit'
    | '/product-content-displays/$id/edit'
    | '/product-content-features/$id/edit'
    | '/product-contents/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/500'
    | '/otp'
    | '/sign-in'
    | '/auth/sign-in'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/'
    | '/brands/create'
    | '/customers/customerCrud'
    | '/product-category-firsts/create'
    | '/product-category-seconds/create'
    | '/product-content-details/create'
    | '/product-content-displays/create'
    | '/product-content-features/create'
    | '/product-contents/create'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/brands'
    | '/chats'
    | '/customers'
    | '/dashboards'
    | '/help-center'
    | '/product-carts'
    | '/product-category-firsts'
    | '/product-category-seconds'
    | '/product-content-details'
    | '/product-content-displays'
    | '/product-content-features'
    | '/product-contents'
    | '/products'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/brands/$id/edit'
    | '/product-category-firsts/$id/edit'
    | '/product-category-seconds/$id/edit'
    | '/product-content-details/$id/edit'
    | '/product-content-displays/$id/edit'
    | '/product-content-features/$id/edit'
    | '/product-contents/$id/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/500'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/auth/sign-in'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(auth)/'
    | '/_authenticated/brands/create'
    | '/_authenticated/customers/customerCrud'
    | '/_authenticated/product-category-firsts/create'
    | '/_authenticated/product-category-seconds/create'
    | '/_authenticated/product-content-details/create'
    | '/_authenticated/product-content-displays/create'
    | '/_authenticated/product-content-features/create'
    | '/_authenticated/product-contents/create'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/apps/'
    | '/_authenticated/brands/'
    | '/_authenticated/chats/'
    | '/_authenticated/customers/'
    | '/_authenticated/dashboards/'
    | '/_authenticated/help-center/'
    | '/_authenticated/product-carts/'
    | '/_authenticated/product-category-firsts/'
    | '/_authenticated/product-category-seconds/'
    | '/_authenticated/product-content-details/'
    | '/_authenticated/product-content-displays/'
    | '/_authenticated/product-content-features/'
    | '/_authenticated/product-contents/'
    | '/_authenticated/products/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/brands/$id/edit'
    | '/_authenticated/product-category-firsts/$id/edit'
    | '/_authenticated/product-category-seconds/$id/edit'
    | '/_authenticated/product-content-details/$id/edit'
    | '/_authenticated/product-content-displays/$id/edit'
    | '/_authenticated/product-content-features/$id/edit'
    | '/_authenticated/product-contents/$id/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  auth500Route: typeof auth500Route
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  AuthSignInRoute: typeof AuthSignInRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignIn2LazyRoute: typeof authSignIn2LazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
  authIndexRoute: typeof authIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  auth500Route: auth500Route,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  AuthSignInRoute: AuthSignInRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignIn2LazyRoute: authSignIn2LazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
  authIndexRoute: authIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/500",
        "/(auth)/otp",
        "/(auth)/sign-in",
        "/auth/sign-in",
        "/(auth)/forgot-password",
        "/(auth)/sign-in-2",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503",
        "/(auth)/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/settings",
        "/_authenticated/brands/create",
        "/_authenticated/customers/customerCrud",
        "/_authenticated/product-category-firsts/create",
        "/_authenticated/product-category-seconds/create",
        "/_authenticated/product-content-details/create",
        "/_authenticated/product-content-displays/create",
        "/_authenticated/product-content-features/create",
        "/_authenticated/product-contents/create",
        "/_authenticated/apps/",
        "/_authenticated/brands/",
        "/_authenticated/chats/",
        "/_authenticated/customers/",
        "/_authenticated/dashboards/",
        "/_authenticated/help-center/",
        "/_authenticated/product-carts/",
        "/_authenticated/product-category-firsts/",
        "/_authenticated/product-category-seconds/",
        "/_authenticated/product-content-details/",
        "/_authenticated/product-content-displays/",
        "/_authenticated/product-content-features/",
        "/_authenticated/product-contents/",
        "/_authenticated/products/",
        "/_authenticated/tasks/",
        "/_authenticated/users/",
        "/_authenticated/brands/$id/edit",
        "/_authenticated/product-category-firsts/$id/edit",
        "/_authenticated/product-category-seconds/$id/edit",
        "/_authenticated/product-content-details/$id/edit",
        "/_authenticated/product-content-displays/$id/edit",
        "/_authenticated/product-content-features/$id/edit",
        "/_authenticated/product-contents/$id/edit"
      ]
    },
    "/(auth)/500": {
      "filePath": "(auth)/500.tsx"
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx"
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/appearance",
        "/_authenticated/settings/display",
        "/_authenticated/settings/notifications",
        "/_authenticated/settings/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.lazy.tsx"
    },
    "/(auth)/sign-in-2": {
      "filePath": "(auth)/sign-in-2.lazy.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.lazy.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.lazy.tsx"
    },
    "/(auth)/": {
      "filePath": "(auth)/index.tsx"
    },
    "/_authenticated/brands/create": {
      "filePath": "_authenticated/brands/create.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/customers/customerCrud": {
      "filePath": "_authenticated/customers/customerCrud.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-category-firsts/create": {
      "filePath": "_authenticated/product-category-firsts/create.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-category-seconds/create": {
      "filePath": "_authenticated/product-category-seconds/create.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-content-details/create": {
      "filePath": "_authenticated/product-content-details/create.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-content-displays/create": {
      "filePath": "_authenticated/product-content-displays/create.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-content-features/create": {
      "filePath": "_authenticated/product-content-features/create.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-contents/create": {
      "filePath": "_authenticated/product-contents/create.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/appearance": {
      "filePath": "_authenticated/settings/appearance.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/display": {
      "filePath": "_authenticated/settings/display.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/notifications": {
      "filePath": "_authenticated/settings/notifications.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/apps/": {
      "filePath": "_authenticated/apps/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/brands/": {
      "filePath": "_authenticated/brands/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/chats/": {
      "filePath": "_authenticated/chats/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/customers/": {
      "filePath": "_authenticated/customers/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboards/": {
      "filePath": "_authenticated/dashboards/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/help-center/": {
      "filePath": "_authenticated/help-center/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-carts/": {
      "filePath": "_authenticated/product-carts/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-category-firsts/": {
      "filePath": "_authenticated/product-category-firsts/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-category-seconds/": {
      "filePath": "_authenticated/product-category-seconds/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-content-details/": {
      "filePath": "_authenticated/product-content-details/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-content-displays/": {
      "filePath": "_authenticated/product-content-displays/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-content-features/": {
      "filePath": "_authenticated/product-content-features/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-contents/": {
      "filePath": "_authenticated/product-contents/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/products/": {
      "filePath": "_authenticated/products/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/tasks/": {
      "filePath": "_authenticated/tasks/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/users/": {
      "filePath": "_authenticated/users/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/brands/$id/edit": {
      "filePath": "_authenticated/brands/$id/edit.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-category-firsts/$id/edit": {
      "filePath": "_authenticated/product-category-firsts/$id/edit.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-category-seconds/$id/edit": {
      "filePath": "_authenticated/product-category-seconds/$id/edit.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-content-details/$id/edit": {
      "filePath": "_authenticated/product-content-details/$id/edit.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-content-displays/$id/edit": {
      "filePath": "_authenticated/product-content-displays/$id/edit.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-content-features/$id/edit": {
      "filePath": "_authenticated/product-content-features/$id/edit.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product-contents/$id/edit": {
      "filePath": "_authenticated/product-contents/$id/edit.lazy.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
